<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title><?php echo $this->title; ?> - PHP Directory Lister</title>
	<link rel="stylesheet" type="text/css" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />
	<? if ($this->css): ?>
		<link rel="stylesheet" type="text/css" href="<?= $this->css ?>" />
	<? endif; ?>

	<link rel="shortcut icon" href="/images/icons/folder_explore.png" />

	<meta name="keywords" content="directory lister, php, Chris Kankiewicz" />
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

	<script type="text/javascript" src="/js/jquery.js"></script>
	<? if ($this->js): ?>
		<script type="text/javascript" src="<?= $this->js ?>"></script>
	<? endif; ?>
	<script type="text/javascript">
	$(document).ready(function(){
		$('a[rel="demo"]').click( function() {
	        window.open( $(this).attr('href'), "_blank", "width=800,height=600,menubar=0,toolbar=1,scrollbars=1" );
	        return false;
	    });
	});
	window.google_analytics_uacct = "UA-967293-11";
	</script>
</head>

<body>

<div id="wrap">


	<div id="main" class="clearfix">
		<!--[if lte IE 7]>
		<div id="old-browser">
			<div class="width-constraint">
				<p><strong>ATTENTION:</strong> Your browser is out of date! <a href="/update-browser">Click here to learn more</a>.</p>
			</div>
		</div>
		<![endif]-->

		<div id="header">
			<div class="width-constraint">
				<div id="site-logo">
					<a href="/"><img src="/images/directory-lister-logo.png" alt="Directory Lister" title="PHP Directory Lister" /></a>
				</div>
				<div id="download">
					<ul class="dl-box">
						<li>
							<a title="Download Directory Lister" href="/downloads/directory-lister-latest.zip">
								<strong>Download Directory Lister</strong>
								<span class="version">v1.0.4</span>
								<br/>
								<span class="updated">Last Updated: <?php if (file_exists('/downloads/directory-lister-latest.zip')) { echo(date("F jS, Y", filemtime('/downloads/directory-lister-latest.zip'))); } else { echo('UNKNOWN'); } ?></span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<div id="sub-header">
			<div class="width-constraint">
				<div id="adsense">
					<script type="text/javascript"><!--
						google_ad_client = "pub-2614997598856289";
						/* Directory Lister */
						google_ad_slot = "4637019490";
						google_ad_width = 728;
						google_ad_height = 15;
						//-->
					</script>
					<script type="text/javascript"
						src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			</div>
		</div>

		<div id="content-wrapper" class="clearfix">
			<div class="width-constraint">

				<div id="content">
					<?= $this->layout()->content; ?>
				</div>

				<div id="right-bar">
					<ul>
						<li><a href="/"><img src="/images/icons/house.png" alt="Home" />Home</a></li>
						<li><a href="/demo" rel="demo"><img src="/images/icons/application_view_list.png" alt="View" />View the Demo</a></li>
						<li><a href="/download"><img src="/images/icons/server_go.png" alt="download" />All Downloads</a></li>
						<li><a href="/installation"><img src="/images/icons/page_white_text.png" alt="Instructions" />Installation Instructions</a></li>
						<li><a href="/license"><img src="/images/icons/page_white_stack.png" alt="License" />Liscensing Information</a></li>
						<li><a href="http://github.com/PHLAK/directory-lister/issues"><img src="/images/icons/bug_edit.png" alt="Bugs" />Report a Bug</a></li>
						<li><a href="/contact-us"><img src="/images/icons/comments_add.png" alt="Contact" />Contact Us</a></li>
					</ul>

					<h3>Directory Lister on GitHub</h3>
					<p>Follow Directory Lister development on <a href="https://github.com/PHLAK/directory-lister">GitHub</a>, the social coding platform.</p>
					<!--<div id="github">
						<a href="https://github.com/PHLAK/directory-lister"><img src="/images/github.png" alt="Github" title="Directory Lister on Github" /></a>
					</div>-->

					<h3>Share Directory Lister</h3>
					<p>Promote Directory Lister through your favorite social networks!</p>
					<div id="social-icons">
						<a href="http://digg.com/http://www.directorylister.com"><img src="/images/social-icons/digg.png" alt="Digg" title="Digg it" /></a>
						<a href="http://del.icio.us/post?url=http://www.directorylister.com&amp;title=Quick%20and%20Simple%20PHP%20directory%20lister"><img src="/images/social-icons/delicious.png" alt="Delicious" title="Share on Delicious" /></a>
						<a href="http://www.reddit.com/submit/?url=http://www.directorylister.com&amp;title=Quick%20and%20Simple%20PHP%20Directory%20Lister"><img src="/images/social-icons/reddit.png" alt="Reddit" title="Share on Reddit" /></a>
						<a href="http://twitter.com/home?status=Check%20out%20http://www.directorylister.com,%20a%20simple,%20new%20PHP%20Directory%20Lister.%20%23php%20%23directorylister%20%23webdevelopment"><img src="/images/social-icons/twitter.png" alt="Twitter" title="Tweet it" /></a>
						<a href="http://www.stumbleupon.com/submit?url=http://www.directorylister.com/"><img src="/images/social-icons/stumbleupon.png" alt="Stumbleupon" title="Stumble it" /></a>
						<a href="http://www.facebook.com/share.php?u=http://www.directorylister.com/"><img src="/images/social-icons/facebook.png" alt="Facebook" title="Share on Facebook" /></a>
						<a href="http://www.google.com/bookmarks/mark?op=edit&amp;bkmk=http://www.directorylister.com&amp;title=PHP%20Directory%20Lister"><img src="/images/social-icons/google.png" alt="Google Bookmarks" title="Add to Google Bookmarks" /></a>
					</div>
				</div>

			</div>
		</div>

		<div id="ad-wrapper">
			<div class="width-constraint">

				<center>
					<script type="text/javascript"><!--
						google_ad_client = "pub-2614997598856289";
						/* Directory Lister Large Bottom */
						google_ad_slot = "5922890614";
						google_ad_width = 728;
						google_ad_height = 90;
					//-->
					</script>
						<script type="text/javascript"
						src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</center>

			</div>
		</div>

	</div>

</div>

<div id="footer">
	<div class="width-constraint">
		<div class="left">
			<a href="http://www.directorylister.com">Directory Lister</a> &middot; <a href="/sitemap.txt">Sitemap</a>
			<br /><br />
			Copyright &copy; <?php echo(date('Y')); ?> &middot; <a href="/license">Some Rights Reserved</a>
		</div>
		<div class="right">
			Web design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a>
			<br /><br />
			Valid <a href="http://validator.w3.org/check?uri=http://www.directorylister.com">XHTML</a> and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>
		</div>
	</div>
</div>

<!-- GOOGLE ANALYTICS -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-967293-11");
pageTracker._trackPageview();
} catch(err) {}</script>
<!-- /GOOGLE ANALYTICS -->

</body>
</html>
