<h1>PHP Directory Lister Script</h1>
<p>Directory Lister is a simple PHP based script created to let you list the contents of a directory and all it's sub-directories and allow you to navigate there within. Just download and install Directory Lister to any web directory and have immediate access to all files and sub-direcories under that directory.</p>

<br />

<h2>Works in All Major Browsers</h2>
<p>Directory Lister has been tested with all major browsers (and several non-major ones) to ensure the best experience to the maximum number of users.  This ensures you and your users, no matter what browser they're using, will have the best possible experience when using Directory Lister.</p>
<img src="images/browsers/icons/firefox.gif" alt="Firefox" title="Firefox" />
<img src="images/browsers/icons/internet-explorer.gif" alt="Internet Explorer" title="Internet Explorer 6+" />
<img src="images/browsers/icons/google-chrome.gif" alt="Google Chrome" title="Google Chrome" />
<img src="images/browsers/icons/safari.gif" alt="Safari" title="Safari" />
<img src="images/browsers/icons/opera.gif" alt="Opera" title="Opera" />
<img src="images/browsers/icons/netscape-navigator.gif" alt="Netscape Navigator" title="Netscape Navigator" />
<p><a href="/browsers" class="go">See full list of tested browsers</a></p>