<h1>Update Your Browser</h1>
<p>We have detected that you are using and outdated version of <?php echo($this->browser); ?>.  In order to assure you are getting the best possible experience while on the web, we suggest upgrading to one of the following current browsers:</p>
<ul class="bulleted-list">
	<li><a href="http://www.getfirefox.com"><b>Mozilla Firefox</b></a></li>
	<li><a href="http://www.google.com/chrome">Google Chrome</a></li>
	<li><a href="http://www.apple.com/safari/">Apple Safari</a></li>
	<li><a href="http://www.opera.com/">Opera</a></li>
</ul>

<div class="hr"><hr /></div>

<p><small>Alternatively, you may upgrade to the latest version of <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx">Internet Explorer</a>, however, due to IE's closed source nature and lack of support for current web standards we advise against this.</small></p>
