<h1>Contact Us</h1>

<p>We provide several methods for getting in contact with us because we value the input of our users.  Please choose the method that best suits your needs and give us a hollar, we're allways happy to hear from you you! </p>

<div class="hr"><hr /></div>

<h2>Email</h2>
<p>To contact Directory Lister by email, please send write to <a href="mailto:Feedback@DirectoryLister.com?subject=Directory%20Lister%20Feedback">Feedback@DirectoryLister.com</a></p>

<div class="hr"><hr /></div>

<h2>Twitter</h2>
<p>For everyone on the Web 2.0 bandwaggon, follow Directory Lister on Twitter at <a href="http://twitter.com/directorylister">@directorylister</a></p>

<div class="hr"><hr /></div>

<h2>GitHub</h2>
<p>Already follwing us on GitHub?  <a href="http://github.com/inbox/new/PHLAK">Send a message to us directly</a></p>
<p><b>NOTE:</b> Must be registered and logged in</p>

<div class="hr"><hr /></div>

<h2>Report a Bug</h2>
<p>Find a problem or bug with Directory Lister, <a href="http://github.com/PHLAK/directory-lister/issues">open an issue</a> on GitHub (Must be registered and logged in) or email us at <a href="mailto:Feedback@DirectoryLister.com?subject=Directory%20Lister%20Bug">Feedback@DirectoryLister.com</a>.</p>