<h1>Contact Us</h1>

<p>As then end user, we're allways happy to hear from you you! There are several methods for getting ahold of us so find your preferd method below.</p>

<div class="hr"><hr /></div>

<h2>Email</h2>
<p>If you would like to contact us, please send an email to <a href="mailto:Feedback@DirectoryLister.com?subject=Directory%20Lister%20Feedback">Feedback@DirectoryLister.com</a></p>

<div class="hr"><hr /></div>

<h2>Twitter</h2>
<p>Contact via Twitter</p>

<div class="hr"><hr /></div>

<h2>GitHub</h2>
<p>Contact via GitHub</p>

<div class="hr"><hr /></div>

<h2>Report a Bug</h2>
<p>Report a bug</p>