<h1>Installation Instructions</h1>
<p>The process to install Directory Lister is simple:</p>
<ol class="numbered-list">
	<li>Download and extract directory lister</li>
	<li>Connect to your server and upload index.php and the .directory-lister folder to the directory you would like to list</li>
	<li>Upload additional files to the same directory as index.php</li>
	<li>Use your web browser to navigate to the directory in which you installed Directory Lister</li>
</ol>
<br />
<p><strong>That's it!</strong>  You should now see a listing of the contents of that directory.</p>

<div class="hr"><hr /></div>

<h2>Need more help?</h2>

<p>View the full installation tutorial for a detailed explanation on installing Directory Lister</p>

<p><a href="/installation/full" class="go">View Full Installation Tutorial</a></p>