<h1>Download Directory Lister</h1>

<ul class="dl-box">
	<li>
		<a title="Download Directory Lister" href="/downloads/directory-lister-latest.zip">
			<strong>Download Latest Version</strong>
			<span class="version">v1.0.0</span>
			<br/>
			<span class="updated">Last Updated: <?php echo(date("F jS, Y", filemtime('downloads/directory-lister-latest.zip'))); ?></span>
		</a>
	</li>
</ul>

<br />

<h2>Older Versions</h2>
<ul class="bulleted-list">
	<li>No Older Versions</li>
</ul>