<h1>Download Directory Lister</h1>

<ul class="dl-box">
	<li>
		<a title="Download Directory Lister" href="/downloads/directory-lister-latest.zip">
			<strong>Download Latest Version</strong>
			<span class="version">v1.0.7</span>
			<br/>
			<span class="updated">Last Updated: <?php if (file_exists('/downloads/directory-lister-latest.zip')) { echo(date("F jS, Y", filemtime('/downloads/directory-lister-latest.zip'))); } else { echo('UNKNOWN'); } ?></span>
		</a>
	</li>
</ul>

<br />

<h2>Older Versions</h2>
<ul class="bulleted-list">
	<li><a href="/downloads/archive/directory-lister-1.0.4.zip">Directory Lister 1.0.4</a></li>
	<li><a href="/downloads/archive/directory-lister-1.0.3.zip">Directory Lister 1.0.3</a></li>
	<li><a href="/downloads/archive/directory-lister-1.0.2.zip">Directory Lister 1.0.2</a></li>
	<li><a href="/downloads/archive/directory-lister-1.0.1.zip">Directory Lister 1.0.1</a></li>
	<li><a href="/downloads/archive/directory-lister-1.0.0.zip">Directory Lister 1.0.0</a></li>
</ul>