<h1>Licensing Information</h1>
<p><b>Directory Lister is Copyright &copy; 2009 Chris Kankiewicz</b></p>

<p>This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.</p>

<p>This program is distributed in the hope that it will be useful,
but without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.  See the
GNU General Public License for more details.</p>

<p><a href="/license/full" class="go">View the full license</a></p>