<h1>All Tested Browsers</h1>

<p>Directory Lister is coded to web standards and tested rigorously to make sure it will work in all major browsers and as many others as possible.  For the end user, this means you can rest assured that Directory Lister will just work.</p>

<img src="images/browsers/icons/firefox.gif" alt="Firefox" title="Firefox" />
<img src="images/browsers/icons/internet-explorer.gif" alt="Internet Explorer" title="Internet Explorer" />
<img src="images/browsers/icons/google-chrome.gif" alt="Google Chrome" title="Google Chrome" />
<img src="images/browsers/icons/safari.gif" alt="Safari" title="Safari" />
<img src="images/browsers/icons/opera.gif" alt="Opera" title="Opera" />
<img src="images/browsers/icons/netscape-navigator.gif" alt="Netscape Navigator" title="Netscape Navigator" />
<img src="images/browsers/icons/avant.gif" alt="Avant" title="Avant" />
<img src="images/browsers/icons/flock.gif" alt="Flock" title="Flock" />
<img src="images/browsers/icons/iceweasel.gif" alt="Iceweasel" title="Iceweasel" />
<img src="images/browsers/icons/sea-monkey.gif" alt="SeaMonkey" title="SeaMonkey" />

<div class="hr"><hr /></div>

<h2>Known Compatible Browsers</h2>

<p>Directory Lister has been confirmed to work properly in each of the following browsers:</p>

<div id="browser-list" class="clearfix">
	<div class="left">
		<ul class="bulleted-list">
			<li>Firefox 3.5</li>
			<li>Firefox 3</li>
			<li>Firefox 2</li>
			<li>Firefox 1</li>
			<li>Internet Explorer 8</li>
			<li>Internet Explorer 7</li>
			<li>Internet Explorer 6</li>
			<li>Google Chrome 2.0</li>
			<li>Google Chrome 1.0</li>
			<li>Safari 4</li>
			<li>Safari 3</li>
			<li>Opera 10</li>
			<li>Opera 9</li>
			<li>Netscape Navigatior 9</li>
			<li>Netscape Navigatior 8</li>
			<li>Flock 2</li>
			<li>Flock 1</li>
			<li>Seamonkey 2</li>
			<li>Seamonkey 1</li>
			<li>Avant 11</li>
			<li>Epiphany 2</li>
			<li>Iceweasel 3</li>
			<li>Kazehakase 0.5</li>
			<li>Melon 1.5</li>
			<li>Shiretoko 3.5</li>
		</ul>
	</div>
	<div class="right">
		<a href="/images/browsers/screenshots/firefox3.png" title="Firefox 3" class="thickbox"><img src="/images/browsers/screenshots/thumbs/firefox3.png" alt="Firefox 3" /></a><br />Firefox 3<br /><br />
		<a href="/images/browsers/screenshots/ie8.png" title="Internet Explorer 8" class="thickbox"><img src="/images/browsers/screenshots/thumbs/ie8.png" alt="Internet Explorer 8" /></a><br />Internet Explorer 8<br /><br />
		<a href="/images/browsers/screenshots/chrome2.png" title="Google Chrome 2" class="thickbox"><img src="/images/browsers/screenshots/thumbs/chrome2.png" alt="Google Chrome 2" /></a><br />Google Chrome 2<br /><br />
	</div>
</div>

<div class="hr"><hr /></div>

<h2>Browsers with Display Errors</h2>

<p>Directory Lister fully functions, but is not displayed properly, in the following browsers:</p>

<ul class="bulleted-list">
	<li>Internet Explorer 5.5</li>
	<li>Opera 8</li>
	<li>Opera 7</li>
	<li>Iceape 1.1</li>
</ul>