<h1>All Tested Browsers</h1>

<p>Directory Lister is coded to standards and tested rigorously to make sure it will work in all major browsers and as many others as possible.  For the end user, this means you can rest assured that Directory Lister will just work.</p>

<img src="images/browsers/firefox.gif" alt="Firefox" title="Firefox" />
<img src="images/browsers/internet-explorer.gif" alt="Internet Explorer" title="Internet Explorer 6+" />
<img src="images/browsers/google-chrome.gif" alt="Google Chrome" title="Google Chrome" />
<img src="images/browsers/safari.gif" alt="Safari" title="Safari" />
<img src="images/browsers/opera.gif" alt="Opera" title="Opera" />
<img src="images/browsers/netscape-navigator.gif" alt="Netscape Navigator" title="Netscape Navigator" />

<br /><br />

<h2>The List</h2>

<p>Directory Lister has been confirmed to work properly in all of the following are browsers:</p>

<ul class="bulleted-list">
	<li>Firefox 3</li>
	<li>Firefox 2 (?)</li>
	<li>Internet Explorer 8</li>
	<li>Internet Explorer 7</li>
	<li>Internet Explorer 6</li>
	<li>Google Chrome</li>
	<li>Safari</li>
	<li>Opera</li>
	<li>Netscape Navigatior (?)</li>
</ul>