<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>PHP Directory Lister</title>
	<link rel="stylesheet" type="text/css" href="/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />

	<link rel="shortcut icon" href="/images/icons/folder_explore.png" />

	<meta name="keywords" content="directory lister, php, Chris Kankiewicz" />

	<script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery.corner.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
		$('.dl-box li a').corner();

		$('a[rel="demo"]').click( function() {
	        window.open( $(this).attr('href'), "_blank", "width=800,height=600,menubar=0,toolbar=1,scrollbars=1" );
	        return false;
	    });
	});
	</script>
</head>

<body>

<div id="wrap">


	<div id="main" class="clearfix">
		<!--[if lte IE 7]>
		<div id="old-browser">
			<div class="width-constraint">
				<p><strong>ATTENTION:</strong> Your browser is out of date! <a href="/update-browser">Click here to learn more</a>.</p>
			</div>
		</div>
		<![endif]-->

		<div id="header">
			<div class="width-constraint">
				<div id="site-logo">
					<a href="/"><img src="/images/directory-lister-logo.png" alt="Directory Lister" title="PHP Directory Lister" /></a>
				</div>
				<div id="download">
					<ul class="dl-box">
						<li>
							<a title="Download Directory Lister" href="/downloads/directory-lister-latest.zip">
								<strong>Download Directory Lister</strong>
								<span class="version">v1.0.0</span>
								<br/>
								<span class="updated">Last Updated: <?php echo(date("F jS, Y", filemtime('downloads/directory-lister-latest.zip'))); ?></span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<div id="sub-header">
			<div class="width-constraint">
				<div id="adsense">
					<a href="#">Advertisment</a>
					<a href="#">Advertisment</a>
					<a href="#">Advertisment</a>
					<a href="#">Advertisment</a>
				</div>
			</div>
		</div>

		<div id="content-wrapper">
			<div class="width-constraint">
				<div id="content">
					<?= $this->layout()->content; ?>
				</div>

				<div id="right-bar">
					<ul>
<!--						<li><a href="/"><img src="/images/icons/house.png" />Home</a></li>-->
						<li><a href="/demo" rel="demo"><img src="/images/icons/application_view_list.png" />View the Demo</a></li>
						<li><a href="/download"><img src="/images/icons/server_go.png" />All Downloads</a></li>
						<li><a href="/installation"><img src="/images/icons/page_white_text.png" />Installation Instructions</a></li>
<!--						<li><a href="/license"><img src="/images/icons/page_white_stack.png" />Liscensing Information</a></li>-->
						<li><a href="http://github.com/PHLAK/directory-lister/issues"><img src="/images/icons/bug_edit.png" />Report a Bug</a></li>
						<li><a href="/feedback"><img src="/images/icons/comments_add.png" />Leave Feedback</a></li>
					</ul>

					<h3>Directory Lister on GitHub</h3>
					<p>Follow Directory Lister development on GitHub, the social coding platform.</p>
					<div id="github">
						<a href="https://github.com/PHLAK/directory-lister"><img src="/images/github.png" alt="Github" title="Directory Lister on Github" /></a>
					</div>

					<h3>Share Directory Lister</h3>
					<p>Promote Directory Lister through your favorite social networks!</p>
					<div id="social-icons">
						<a href="http://digg.com/http://www.directorylister.com"><img src="/images/social-icons/digg.png" alt="digg" title="Digg it" /></a>
						<a href="http://del.icio.us/post?url=http://www.directorylister.com&title=Quick%20and%20Simple%20PHP%20directory%20lister"><img src="/images/social-icons/delicious.png" alt="Delicious" title="Share on Delicious" /></a>
						<a href="http://www.reddit.com/submit/?url=http://www.directorylister.com&amp;title=Quick%20and%20Simple%20PHP%20Directory%20Lister"><img src="/images/social-icons/reddit.png" alt="digg" title="Reddit" /></a>
						<a href="http://twitter.com/home?status=Check%20out%20http://www.directorylister.com,%20a%20simple,%20new%20PHP%20Directory%20Lister.%20%23php%20%23directorylister%20%23webdevelopment"><img src="/images/social-icons/twitter.png" alt="Twitter" title="Tweet it" /></a>
						<a href="http://www.stumbleupon.com/submit?url=http://www.directorylister.com/"><img src="/images/social-icons/stumbleupon.png" alt="Stumbleupon" title="Stumble it" /></a>
						<a href="http://www.google.com/bookmarks/mark?op=edit&amp;bkmk=http://www.directorylister.com&amp;title=PHP%20Directory%20Lister"><img src="/images/social-icons/google.png" alt="Google Bookmarks" title="Add to Google Bookmarks" /></a>
						<a href="http://www.facebook.com/share.php?u=http://www.directorylister.com/"><img src="/images/social-icons/facebook.png" alt="Facebook" title="Share on Facebook" /></a>
					</div>
				</div>
			</div>
		</div>

	</div>

</div>

<div id="footer">
	<div class="width-constraint">
		<div class="left">
			<a href="http://www.directorylister.com">Directory Lister</a>
			<br /><br />
			&copy; <?php echo(date('Y')); ?> &middot; Some Rights Reserved
		</div>
		<div class="right">
			Web design by, <a href="http://www.chriskankiewicz.com">Chris Kankiewicz</a>
			<br /><br />
			Valid <a href="http://validator.w3.org/check?uri=http://www.directorylister.com">XHTML</a> and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>
		</div>
	</div>
</div>

<!-- GOOGLE ANALYTICS -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-967293-11");
pageTracker._trackPageview();
} catch(err) {}</script>
<!-- /GOOGLE ANALYTICS -->

</body>
</html>
